### ISSUE TITLE
How is mask is used for ?

### ISSUE THREAD

**Issue by aliubimov** [openai/ecprice-neural-gpu#1]
Hi, 

I am trying to understand implementation from original paper. And I see you use mask for some reason, which is not covered in the white paper.  Can you please, explain, what role does mask plays in LSTM cell ?

https://github.com/openai/neural-gpu/blob/9f37c0d3f13f79e28876ab064a17e0f6c70f8e89/neuralgpu/model.py#L105

**Comment by ecprice** [comment]
Because constructing the computation graph is kind of slow, we don't do this for every possible length -- just certain, roughly exponentially increasing lengths.  Each NeuralGPUAtSize instance can do computation up to a given max length.

So if you want to do a 13 digit computation, you might use the size-16 instance.  But the result of the computation shouldn't depend on whether you're using a size-13 or size-16 or size-100 NeuralGPUAtSize instance; that should only affect running time.

The way we achieve this is with the mask, which zeros out everything outside the problem instance at every stage.  That is, it zeros out everything but the 13 digits, so a NeuralGPUAtSize of length 16 acts like one of length 13.

**Comment by aliubimov** [comment]
Thanks for detailed explanation.
